-- Seed data for Selk marketplace
-- Assigns all listings to user_id=1 (test@example.com)

INSERT INTO listings (user_id, title, description, type, city, country, size_sqm, price_sqm, amenities, rating, review_count, free_cancel, insurance) VALUES
(1, 'Premium Climate Warehouse — Muscat Industrial', 'State-of-the-art climate-controlled warehouse in Muscat''s industrial zone. 24/7 security, loading docks, and direct highway access. Ideal for sensitive goods storage.', 'warehouse', 'Muscat', 'OM', 2400, 18.50, '{"24/7 access","loading dock","CCTV","climate control","forklift"}', 9.2, 47, true, true),
(1, 'Secure Container Yard — Sohar Port', 'Fenced container storage adjacent to Sohar Port. Ground-level access, flood-lit 24/7, customs-bonded zone available. Short and long-term rates.', 'container', 'Sohar', 'OM', 800, 12.00, '{"24/7 access","CCTV","customs bonded","ground level"}', 8.6, 23, true, false),
(1, 'Shared Basement Unit — CBD Muscat', 'Clean, dry basement storage in the Muscat CBD. Perfect for document archiving or small-inventory businesses. Elevator access.', 'basement', 'Muscat', 'OM', 120, 25.00, '{"elevator access","dry storage","fire suppression"}', 7.8, 12, false, false),
(1, 'Open-Air Yard — Salalah Free Zone', 'Large open yard near Salalah port, suitable for vehicles, machinery, and bulk materials. Concrete surface, well-drained.', 'outdoor', 'Salalah', 'OM', 5000, 6.50, '{"ground level","24/7 access","concrete surface"}', 8.1, 8, true, false),
(1, 'Climate-Controlled Pharma Vault — Muscat', 'Temperature and humidity-controlled facility meeting pharmaceutical storage standards. Clean room certified, backup power.', 'climate', 'Muscat', 'OM', 350, 42.00, '{"climate control","backup power","clean room","CCTV","fire suppression","24/7 access"}', 9.5, 31, true, true),
(1, 'Double Garage — Al Khuwair', 'Spacious double garage converted for commercial storage. Ground floor, roller door, power and lighting. Quiet residential area.', 'garage', 'Muscat', 'OM', 45, 30.00, '{"ground level","power supply","lighting","roller door"}', 7.2, 5, false, false),
(1, 'Logistics Warehouse — Nizwa', 'Modern logistics warehouse on the Nizwa-Muscat corridor. High ceiling, multiple loading bays, office space included.', 'warehouse', 'Nizwa', 'OM', 3200, 14.00, '{"loading dock","high ceiling","office space","24/7 access","CCTV","parking"}', 8.9, 19, true, true),
(1, 'Reefer Container Storage — Sohar', 'Refrigerated container bays with power hookups. Ideal for perishable goods, seafood exports, and cold chain logistics.', 'container', 'Sohar', 'OM', 600, 22.00, '{"refrigeration","power hookup","24/7 access","CCTV"}', 9.0, 14, true, true),
(1, 'Flex Warehouse — Barka Industrial', 'Versatile warehouse space in Barka, divisible from 200m² to full 1,600m². Shared amenities, managed access.', 'warehouse', 'Barka', 'OM', 1600, 15.50, '{"divisible space","shared amenities","managed access","parking","CCTV"}', 8.3, 22, true, false),
(1, 'Underground Vault — Old Muscat', 'Heritage-zone secure basement vault with dehumidification. Perfect for art, wine, or high-value inventory.', 'basement', 'Muscat', 'OM', 80, 55.00, '{"dehumidification","high security","CCTV","fire suppression","climate control"}', 9.7, 9, false, true),
(1, 'Outdoor Parking & Storage — Seeb', 'Paved outdoor compound near Muscat International Airport. Suitable for vehicle storage, equipment staging, or overflow inventory.', 'outdoor', 'Seeb', 'OM', 3000, 5.00, '{"paved surface","security patrol","lighting","airport proximity"}', 7.5, 6, true, false),
(1, 'Climate Warehouse — Dubai Investment Park', 'Premium temperature-managed warehouse in DIP. Cross-docking facility, staff quarters, advanced fire suppression.', 'climate', 'Dubai', 'AE', 4500, 35.00, '{"climate control","cross-docking","staff quarters","fire suppression","24/7 access","CCTV"}', 9.3, 56, true, true),
(1, 'Container Depot — Jebel Ali', 'High-volume container depot near Jebel Ali Port. Stacking up to 4-high, reach-stacker available on-site.', 'container', 'Dubai', 'AE', 10000, 8.00, '{"container stacking","reach stacker","24/7 access","customs bonded","CCTV"}', 8.8, 42, true, false),
(1, 'Garage Workshop — Al Quoz', 'Commercial garage space in Al Quoz industrial area. Power, compressed air, pit access. Tools not included.', 'garage', 'Dubai', 'AE', 150, 28.00, '{"power supply","compressed air","pit access","roller door","lighting"}', 7.9, 11, false, false),
(1, 'Cold Storage Unit — Riyadh', 'Dedicated cold room in Riyadh logistics hub. Constant -18°C, backup generator, halal-certified facility.', 'climate', 'Riyadh', 'SA', 500, 48.00, '{"deep freeze","backup power","halal certified","24/7 access","CCTV","loading dock"}', 9.1, 27, true, true),
(1, 'Multi-Bay Warehouse — KAEC', 'Multi-tenant warehouse at King Abdullah Economic City. Flexible bay sizes, shared forklift pool, modern facility.', 'warehouse', 'KAEC', 'SA', 2000, 16.00, '{"flexible bays","shared forklift","modern facility","24/7 access","CCTV","parking"}', 8.5, 15, true, false),
(1, 'Secure Basement — Bahrain Bay', 'Premium underground storage in Bahrain Bay financial district. Biometric access, climate-controlled, 24/7 concierge.', 'basement', 'Manama', 'BH', 200, 40.00, '{"biometric access","climate control","concierge","fire suppression","CCTV"}', 9.4, 18, true, true),
(1, 'Open Compound — Doha Industrial Area', 'Large walled compound in Doha Industrial Area. Suitable for construction materials, pipe yards, or equipment staging.', 'outdoor', 'Doha', 'QA', 8000, 4.50, '{"walled compound","security patrol","ground level","lighting","24/7 access"}', 7.6, 7, false, false),
(1, 'Smart Warehouse — Kuwait Free Zone', 'IoT-enabled warehouse with inventory tracking, automated climate, and real-time monitoring dashboard. Premium facility.', 'warehouse', 'Kuwait City', 'KW', 1800, 32.00, '{"IoT tracking","automated climate","real-time monitoring","loading dock","CCTV","24/7 access"}', 9.6, 34, true, true),
(1, 'Vehicle Garage — Muscat Heights', 'Covered garage bays for commercial vehicle storage. Each bay fits vehicles up to 7m. Monthly or annual contracts.', 'garage', 'Muscat', 'OM', 60, 22.00, '{"covered parking","security","lighting","ground level"}', 7.4, 4, false, false);
